name: Checks

on:
  workflow_call:
    inputs:
      node-version:
        default: 18.x
        required: false
        type: string

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: TLS setup
        run: |
          sudo apt update
          sudo apt install -y libnss3-tools
          mkdir -p $HOME/.pki/nssdb
          certutil -d sql:$HOME/.pki/nssdb -N --empty-password

          curl -JL "https://dl.filippo.io/mkcert/latest?for=linux/amd64" -o mkcert
          chmod +x mkcert
          sudo cp ./mkcert /usr/local/bin/
          sudo mkcert -install

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Restore Build Cache
        id: restore-build-cache
        uses: actions/cache/restore@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.sha }}-build

      - name: Install
        run: |
          yarn install --immutable
          yarn tls:config

      - name: Install Playwright
        run: yarn playwright install --with-deps

      - name: Run your tests
        run: yarn test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report