name: Pull Request

env:
  context: './'
  cache-name: cache-release
  node-version: 18.x

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    uses: micro-lc/micro-lc.github.io/.github/workflows/checks.yml@main

  file-changes:
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.filter.outputs.test-files }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            test-files:
              - 'yarn.lock'
              - package.json
              - '.github/workflows/**'
              - 'tests/**'
              - 'src/**'
              - 'applications/**'

  build:
    uses: micro-lc/micro-lc.github.io/.github/workflows/build.yml@main

  e2e-tests:
    needs:
      - build
      - file-changes
    if: needs.file-changes.outputs.test-files == 'true'
    uses: micro-lc/micro-lc.github.io/.github/workflows/playwright-tests.yml@main
